#Data Server - Localhost
server:
  servlet:
    context-path: /movies_alkemy
  port: 8080

#Logs en Consola
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    dateformat: hh:mm

#Conexión MySQL y Querys
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disney_movies?autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#Otras config de Spring
  main:
    banner-mode: off
#  thymeleaf:
#    cache: false
  mvc:
    format:
      date: yyyy-MM-dd
#Transacciones de Mail
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            required: true
#            enable: true
#          ssl:
#            trust: smtp.gmail.com
