#Data Server - Localhost
server:
  servlet:
    context-path: /movies_alkemy
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

#Logs en Consola
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    dateformat: hh:mm

#Conexión MySQL y Querys
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disney_movies?autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#Otras config de Spring
  main:
    banner-mode: off
#  thymeleaf:
#    cache: false
  mvc:
    format:
      date: yyyy-MM-dd
    throw-exception-if-no-handler-found: true
#Transacciones de Mail
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            required: true
#            enable: true
#          ssl:
#            trust: smtp.gmail.com
  application:
    name: disney-movie-api
  jackson:
    property-naming-strategy: SNAKE_CASE
  web:
    resources:
      add-mappings: false
#  kafka:
#    topics:
#      sampleTopic: alkemy.movies.topic.v1
  api-docs:
    path: /api-docs

documentation:
  openapi:
    info:
      title: Disney Movie API
      description: Disney Movie API documentation
      version: 1.0
      contact:
        name: Marcos G. F. D.
        email: marcos.detti@hotmail.com

management:
  health:
    db.enabled: false
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

api:
  baseUrl: https://jsonplaceholder.typicode.com